add dto and mapper
LeonIllya/jv-book-store pull request #2
Opened 2024-03-05 13:57 UTC by LeonIllya

2024-03-05 19:31 UTC, Vasul-Pankiv requested changes
fix your .gitignore file. Dir .idea, .class, and so on should not be in your pr

2024-03-06 17:41 UTC, olekskov requested changes

2024-03-06 17:41 UTC, olekskov commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +        }
Please use Optional<Book> as return type on repository level instead

2024-03-07 17:40 UTC, okuzan approved these changes

2024-03-08 21:14 UTC, merged