Develop
LeonIllya/jv-book-store pull request #5
Opened 2024-03-15 16:46 UTC by LeonIllya

2024-03-15 19:55 UTC, okuzan requested changes
.idea папки не має бути на гітхабі
git rm --cached -r .idea

2024-03-16 12:10 UTC, olekskov requested changes

2024-03-16 12:10 UTC, olekskov commented on src/main/java/book/store/dto/CreateBookRequestDto.java
> +    @NotNull
Please check ```@NotBlank, @NotEmpty, @ISBN, @Length``` annotations and make validation more precise

2024-03-20 12:39 UTC, kozhukhovsky approved these changes

2024-03-20 18:00 UTC, merged