Develop
LeonIllya/jv-book-store pull request #9
Opened 2024-04-19 08:16 UTC by LeonIllya

Add JWT token

2024-04-19 11:50 UTC, Rommelua approved these changes

2024-04-25 12:40 UTC, kerrrusha requested changes

2024-04-25 12:40 UTC, kerrrusha commented on src/main/java/book/store/model/User.java
> +@EqualsAndHashCode
use this to avoid bugs related to auto-generating equals and hashcode for JPA Entities
```suggestion
@EqualsAndHashCode.of("id")
```

2024-04-25 12:40 UTC, kerrrusha commented on src/main/java/book/store/config/SecurityConfig.java
this file change is not related to the current task "Add Category model", so it should be reverted

2024-04-25 12:40 UTC, kerrrusha commented on src/main/java/book/store/security/AuthenticationService.java
this file change is not related to the current task "Add Category model", so it should be reverted

2024-04-25 12:40 UTC, kerrrusha commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
this file change is not related to the current task "Add Category model", so it should be reverted

2024-04-25 12:40 UTC, kerrrusha commented on src/main/java/book/store/security/JwtUtil.java
this file change is not related to the current task "Add Category model", so it should be reverted

2024-04-25 18:34 UTC, merged